name: main

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
          path: temp
          fetch-depth: 0

      - uses: msys2/setup-msys2@v2
        with:
          msystem: MSYS
          install: git base-devel msys2-devel
          update: true

      - name: Move Checkout
        run: |
          Copy-Item -Path ".\temp" -Destination "C:\_" -Recurse

      - name: CI-Build
        shell: msys2 {0}
        run: |
          cd /C/_
          ./ci-build.sh

      - name: "Upload binaries"
        uses: actions/upload-artifact@v2
        with:
          name: msys2-packages
          path: C:/_/artifacts/*.pkg.tar.*

      - name: "Upload sources"
        uses: actions/upload-artifact@v2
        with:
          name: sources
          path: C:/_/artifacts/*.src.tar.*
